server:
  port: 13100
spring:
  application:
    name: cloud-service-merchant-bet
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
logging:
  level:
    com.xinbo: debug
  file:
    max-size: 5MB
dubbo:
  scan:
    base-packages: com.xinbo.cloud.service.merchant.bet
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    generic: false
  registry:
    address: nacos://127.0.0.1:8848
    check: false

