server:
  port: 13100
spring:
  application:
    name: cloud-service-merchant-bet
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.150:8848
    sentinel:
      transport:
        dashboard: 192.168.30.150:8080
logging:
  level:
    com.xinbo: debug
  file:
    max-size: 5MB
    name: ./logs/${spring.application.name}.log
    max-history: 10
dubbo:
  scan:
    base-packages: com.xinbo.cloud.service.merchant.bet
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    generic: false
  registry:
    address: nacos://192.168.30.150:8848
    check: false