server:
  port: 13100
  servlet:
    context-path: /gw-merchant-bet

#Feign请求超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#开启熔断器
feign:
  sentinel:
    enabled: true

spring:
  application:
    name: cloud-service-merchant-bet

  cloud:
    #熔断器
    sentinel:
      transport:
        port: ${server.port}
        dashboard: 45.125.218.106:8002

    #nacos配置
    nacos:
      discovery:
        server-addr: 45.125.218.106:8848

logging:
  level:
    com.xinbo: debug
  file:
    max-size: 5MB
  path: ./logs/

