FROM openjdk:8-jdk
VOLUME /tmp
ADD cloud-service-merchant-bet.jar app.jar
EXPOSE 13100
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=prod","-Dspring.application.name=cloud-service-merchant-bet","-jar","/app.jar"]